<?php
/**
 * @ copyright Solera
 * @ author Ivan Stankovic 
 * @ created Feb 7, 2015
 * @ description :
 */

if (!$showSuccessMessage) {
    $form = $this->form;
    $form->prepare();
     
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
} else {
    echo "Phone is successfully updated";
}
?>

<a href="<?php echo $this->url('cellphone', array('action' => 'list'));?>">Back</a>
  